/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as nftCollectionSol from './NftCollection.sol/index.js';
export type { nftCollectionSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { NftCollection } from './NftCollection.sol/NftCollection.js';
export { NftCollection__factory } from './factories/NftCollection.sol/NftCollection__factory.js';