/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from './Counter.sol/index.js';
export * as nftCollectionSol from './NftCollection.sol/index.js';